config/routes.rb
Rails.application.routes.draw do
  resources :feedings
  resources :babies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :feedings
end

app/models/feeding.rb
class Feeding < ApplicationRecord
    belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController

  def index
    @babies = Baby.all
  end

  def show
    @baby = Baby.find(params[:id])
    @hoy = 0
    @sum = 0
    @cant = 0
  end

end

app/controllers/feedings_controller.rb
class FeedingsController < ApplicationController
  before_action :set_feeding, only: [:show, :edit, :update, :destroy]

  # GET /feedings
  # GET /feedings.json
  def index
    @feedings = Feeding.all
  end

  # GET /feedings/1
  # GET /feedings/1.json
  def show
  end

  # GET /feedings/new
  def new
    @feeding = Feeding.new
    @babies = Baby.all
  end

  # GET /feedings/1/edit
  def edit
  end

  # POST /feedings
  # POST /feedings.json
  def create
    @feeding = Feeding.new(feeding_params)

    respond_to do |format|
      if @feeding.save
        format.html { redirect_to @feeding, notice: 'Feeding was successfully created.' }
        format.json { render :show, status: :created, location: @feeding }
      else
        format.html { render :new }
        format.json { render json: @feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedings/1
  # PATCH/PUT /feedings/1.json
  def update
    respond_to do |format|
      if @feeding.update(feeding_params)
        format.html { redirect_to @feeding, notice: 'Feeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @feeding }
      else
        format.html { render :edit }
        format.json { render json: @feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedings/1
  # DELETE /feedings/1.json
  def destroy
    @feeding.destroy
    respond_to do |format|
      format.html { redirect_to feedings_url, notice: 'Feeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feeding
      @feeding = Feeding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feeding_params
      params.require(:feeding).permit(:cant, :time, :baby)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/feedings_helper.rb
module FeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>feedings</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.name %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= baby.feedings.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New feeding', new_feeding_path %>

app/views/babies/show.html.erb
<h1>Babies#show</h1>

<strong>Cuantas veces tomo leche hoy: </strong>

<%@baby.feedings.where("created_at LIKE ?", "%#{Time.now.strftime('%Y-%m-%d')}%").each do |v|%>

  <%@hoy += 1%>

<%end%>

<%=@hoy%>

<br>

<strong>Ultima vez que tomo leche: </strong>
<span><%=@baby.feedings.all.last.created_at%></span>


<br>

<strong>Tiempo tomado hoy: </strong>
<%@baby.feedings.where("created_at LIKE ?", "%#{Time.now.strftime('%Y-%m-%d')}%").each do |v|%>
  <%@sum += v.tiempo%>
<%end%>
<span><%=@sum%> minutos</span>

<br>

<strong></strong>

<%@baby.feedings.where("created_at LIKE ?", "%#{Time.now.strftime('%Y-%m-%d')}%").each do |v|%>
  <%@cant += v.cantidad%>
<%end%>
<strong>Cuanto ha tomado hoy:</strong>
<span><%=@cant%> ml</span>
<br>
<%=link_to :back, babies_index_path%>

app/views/feedings/_form.html.erb
<%= form_with(model: feeding, local: true) do |form| %>
  <% if feeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feeding.errors.count, "error") %> prohibited this feeding from being saved:</h2>

      <ul>
      <% feeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cant %>
    <%= form.number_field :cant %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time %>
  </div>

  <div class="field">
    <%= form.label :baby %>
    <%= form.collection_select :baby_id, @babies, :id, :nombre%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedings/edit.html.erb
<h1>Editing Feeding</h1>

<%= render 'form', feeding: @feeding %>

<%= link_to 'Show', @feeding %> |
<%= link_to 'Back', feedings_path %>

app/views/feedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedings</h1>

<table>
  <thead>
    <tr>
      <th>Cant</th>
      <th>Time</th>
      <th>Baby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedings.each do |feeding| %>
      <tr>
        <td><%= feeding.cant %></td>
        <td><%= feeding.time %></td>
        <td><%= feeding.baby.name %></td>
        <td><%= link_to 'Show', feeding %></td>
        <td><%= link_to 'Edit', edit_feeding_path(feeding) %></td>
        <td><%= link_to 'Destroy', feeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feeding', new_feeding_path %>

app/views/feedings/new.html.erb
<h1>New Feeding</h1>

<%= render 'form', feeding: @feeding %>

<%= link_to 'Back', feedings_path %>

app/views/feedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cant:</strong>
  <%= @feeding.cant %>
</p>

<p>
  <strong>Time:</strong>
  <%= @feeding.time %>
</p>

<p>
  <strong>Baby:</strong>
  <%= @feeding.baby.name %>
</p>

<%= link_to 'Edit', edit_feeding_path(@feeding) %> |
<%= link_to 'Back', feedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apuswife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>